#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

current_dir=$(pwd)

ln -sf "${current_dir}"/bashrc ~/.bashrc
ln -sf "${current_dir}"/vimrc ~/.vimrc
ln -sf "${current_dir}"/starship.toml ~/.config/starship.toml

